spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      stats:
        micrometer:
          enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"